name: Release & Build Docker Image to GHCR

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write

env:
  REGISTRY: ghcr.io

jobs:
  release-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install python-semantic-release
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Ensure initial tag exists
        run: |
          if [ -z "$(git tag --list)" ]; then
            git tag v0.0.0
          else
            echo "Initial tag exists, skipping"
          fi

      - name: Semantic Release
        id: semantic_release
        run: semantic-release publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_NAME: fastapi2
          REPO_OWNER: youssefheshamm

      - name: Save release version and image name
        run: |
          VERSION=$(semantic-release version | tr -d '[:space:]')
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
