name: Test Token Secret

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check if TOKEN secret exists
        run: |
          if [ -n "${{ secrets.TOKEN }}" ]; then
            echo "✅ TOKEN secret is accessible and has content"
            echo "Token length: ${#TOKEN_SECRET}"  # Shows length without exposing content
          else
            echo "❌ TOKEN secret is empty or not accessible"
            exit 1
          fi
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN }}
      
      - name: Test basic GitHub API call (safe test)
        run: |
          # Test if we can make authenticated API calls
          response=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/user" | grep -o '"login": "[^"]*' | head -1)
          
          if [ -n "$response" ]; then
            echo "✅ Token authentication successful - $response"
          else
            echo "❌ Token authentication failed"
            exit 1
          fi
      
      - name: Verify token permissions
        run: |
          # Check what scopes the token has
          response=$(curl -s -I -H "Authorization: token ${{ secrets.TOKEN }}" \
            "https://api.github.com/user" | grep -i 'x-oauth-scopes:' || echo "")
          
          if [ -n "$response" ]; then
            echo "Token scopes: $response"
          else
            echo "❌ Could not retrieve token scopes"
            exit 1
          fi
